# Generated by Django 3.2.25 on 2024-06-10 13:57

from django.db import migrations, models
from django.conf import settings

from bugvault.core import set_user_acls


def forwards_func(apps, schema_editor):
    set_user_acls(settings.ALL_GROUPS)
    Flaw = apps.get_model("bugvault", "Flaw")
    Flaw.objects.filter(cve_id="").update(cve_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("bugvault", "0145_audit_history"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop, atomic=True),
    ]
